config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users/index', to: 'user#index'
  get '/photos/index', to: 'photos#index'
  get 'move' => 'user#move', as: :move
  resources :photos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :User
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :User
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @user = User.find(flash[:notice])
    redirect_to action: "show", id: @user.id
  end

  def list
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new

  end



end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
    @size = @users.size
  end

  def move
    @userId = params[:type]
    flash[:notice] = @userId
    redirect_to photos_index_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<h1><%=@users%></h1>

app/views/photos/show.html.erb
<h1><%=@user.first_name%> <%=@user.last_name%></h1>
<% @photos = Photo.where(User_id: @user.id) %>
<% @photos.each do |img|%>
  <% @imgName = img.file_name %>
  <div class = "post">
    <%@poster = User.where(id: img.User_id)%>
    <p class = "poster"><%=@poster[0].first_name%> <%=@poster[0].last_name%> <span class = "date_time">post it at <%=img.date_time%></span></p>
    <%= image_tag @imgName%>
    <% @comment = Comment.where(Photo_id: img.id) %>
    <% @comment.each do |com|%>
      <p class = "com_text">
        <% @user=User.where(id: com.User_id)%>
      <p class = "Commer"><%=link_to @user[0].first_name,move_path(@Uid, :type => @user[0].id) %> <%=@user[0].last_name%> said:</p>
      <p class = "date_time"><%=com.date_time%></p>

      <%=com.comment_text%></p>
    <% end %>
  </div>
  <br>
<% end %>
<style>
  .post {
    font-size: larger;
    border: 3px solid yellow;
  }
  .Commer {
    font-size: large;
    font-style: italic;
  }
  .date_time  {
    font-size: large;
    font-style: italic;
  }

  .poster {
  }
  .com_text {
    border: 5px solid blue;
  }
</style>

app/views/user/index.html.erb
<h1>PhotoSite User list</h1>
<p>There are <%=@size%></p>
<table>
  <tr>
    <th>User</th>
    <th>First</th>
    <th>Last</th>
  </tr>
  <% @users.each do |element| %>
    <tr>
      <td><%=element.id%></td>
      <td><%=link_to element.first_name, move_path(@fn, :type => element)%></td>
      <td><%=link_to element.last_name, move_path(@fn, :type => element)%></td>
    </tr>
  <% end %>

</table>

<style>

</style>